# Generated by Django 3.2.6 on 2021-12-17 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experience_yrs_start', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('language_used', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('Project_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('Project_image', models.ImageField(upload_to='Project/Image')),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profilePic', models.ImageField(upload_to='Portfolio')),
                ('date', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=50)),
                ('contact_num', models.BigIntegerField()),
                ('Nationality', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='Portfolio/pdf')),
                ('Resume_url', models.URLField(blank=True)),
                ('linked_url', models.URLField(blank=True)),
                ('fb_url', models.URLField(blank=True)),
                ('insta_url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('experience', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='Profile.experience')),
            ],
        ),
    ]
